services:
  service-1:
    container_name: service-1
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue
        - PROJECT_NAME=RiderEAPIssue
    networks:
      - rider

  service-2:
    container_name: service-2
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue2
        - PROJECT_NAME=RiderEAPIssue2
    environment:
      - DUMMY=1
    profiles:
      - rider
    depends_on:
      - service-1
    networks:
      - rider

  service-3:
    container_name: service-3
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue3
        - PROJECT_NAME=RiderEAPIssue3
    networks:
      - rider

  service-4:
    container_name: service-4
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue4
        - PROJECT_NAME=RiderEAPIssue4
    networks:
      - rider

  service-5:
    container_name: service-5
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue5
        - PROJECT_NAME=RiderEAPIssue5
    networks:
      - rider

  service-6:
    container_name: service-6
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue6
        - PROJECT_NAME=RiderEAPIssue6
    networks:
      - rider

  service-7:
    container_name: service-7
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue7
        - PROJECT_NAME=RiderEAPIssue7
    networks:
      - rider

  service-48:
    container_name: service-8
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue8
        - PROJECT_NAME=RiderEAPIssue8
    networks:
      - rider

  service-9:
    container_name: service-9
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue9
        - PROJECT_NAME=RiderEAPIssue9
    networks:
      - rider

  service-10:
    container_name: service-10
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue10
        - PROJECT_NAME=RiderEAPIssue10
    networks:
      - rider

  service-11:
    container_name: service-11
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue11
        - PROJECT_NAME=RiderEAPIssue11
    networks:
      - rider

  service-12:
    container_name: service-12
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue12
        - PROJECT_NAME=RiderEAPIssue12
    networks:
      - rider

networks:
  rider:
    external: true
