services:
  service-1:
    container_name: service-1
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue
        - PROJECT_NAME=RiderEAPIssue
    depends_on:
      - camunda

  service-2:
    container_name: service-2
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue2
        - PROJECT_NAME=RiderEAPIssue2
    depends_on:
      - service-1

  service-3:
    container_name: service-3
    build:
      context: ./src/
      args:
        - PROJECT_FOLDER=RiderEAPIssue3
        - PROJECT_NAME=RiderEAPIssue3

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "camunda"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  camunda:
    # https://hub.docker.com/r/camunda/camunda-bpm-platform/
    container_name: camunda-demo
    build:
      context: ./tools/Camunda
      dockerfile: Dockerfile
    command: "./camunda.sh --production"
    ports:
      - "5301:${CAMUNDA_PORT}"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  database:
