# Dummy dockerfile in order to support VS fast mode containers. Why this is needed is described in 'docker-compose.vs.debug.yml'
# See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
